import { Hobby } from ".";

export const data: Hobby[] = [
  {
    name: "Sports",
    score: 90,
    items: [
      {
        name: "Football",
        score: 95,
        items: [
          { name: "Manchester United", score: 85 },
          { name: "Real Madrid", score: 90 },
          { name: "Bayern Munich", score: 75 },
          { name: "Barcelona", score: 85 },
          { name: "Liverpool", score: 80 },
          { name: "PSG", score: 70 },
          { name: "Juventus", score: 65 },
          { name: "AC Milan", score: 60 },
          { name: "Arsenal", score: 70 },
          { name: "Chelsea", score: 75 },
          { name: "Manchester City", score: 75 },
          { name: "Borussia Dortmund", score: 60 },
          { name: "Fantasy Football", score: 50 },
          { name: "Sunday League", score: 30 },
        ],
      },
      {
        name: "Basketball",
        score: 85,
        items: [
          { name: "LA Lakers", score: 80 },
          { name: "Chicago Bulls", score: 70 },
          { name: "Golden State Warriors", score: 75 },
          { name: "Brooklyn Nets", score: 60 },
          { name: "Boston Celtics", score: 65 },
          { name: "Miami Heat", score: 60 },
          { name: "Street Basketball", score: 40 },
          { name: "NBA Fantasy", score: 35 },
          { name: "College Basketball", score: 50 },
          { name: "WNBA", score: 30 },
        ],
      },
      {
        name: "Tennis",
        score: 75,
        items: [
          { name: "Singles", score: 70 },
          { name: "Doubles", score: 50 },
          { name: "Mixed Doubles", score: 40 },
          { name: "Grand Slams", score: 80 },
          { name: "ATP Tour", score: 65 },
          { name: "WTA Tour", score: 55 },
          { name: "Amateur Tennis", score: 35 },
          { name: "Table Tennis", score: 45 },
          { name: "Padel Tennis", score: 25 },
        ],
      },
      {
        name: "Cricket",
        score: 70,
        items: [
          { name: "Test Cricket", score: 60 },
          { name: "ODI", score: 65 },
          { name: "T20", score: 70 },
          { name: "IPL", score: 75 },
          { name: "Big Bash", score: 45 },
          { name: "County Cricket", score: 30 },
          { name: "Club Cricket", score: 25 },
        ],
      },
      {
        name: "Combat Sports",
        score: 65,
        items: [
          { name: "Boxing", score: 75 },
          { name: "MMA", score: 70 },
          { name: "Wrestling", score: 60 },
          { name: "Judo", score: 40 },
          { name: "Karate", score: 45 },
          { name: "Brazilian Jiu-Jitsu", score: 35 },
          { name: "Muay Thai", score: 30 },
          { name: "Taekwondo", score: 35 },
        ],
      },
      {
        name: "Running",
        score: 70,
        items: [
          { name: "Marathon", score: 60 },
          { name: "Trail Running", score: 40 },
          { name: "Sprint", score: 50 },
          { name: "Cross Country", score: 35 },
          { name: "Park Run", score: 45 },
          { name: "Ultra Running", score: 20 },
        ],
      },
      {
        name: "Cycling",
        score: 65,
        items: [
          { name: "Road Cycling", score: 60 },
          { name: "Mountain Biking", score: 50 },
          { name: "BMX", score: 35 },
          { name: "Track Cycling", score: 30 },
          { name: "Cycle Touring", score: 25 },
          { name: "Gravel Biking", score: 20 },
        ],
      },
      {
        name: "Winter Sports",
        score: 55,
        items: [
          { name: "Skiing", score: 65 },
          { name: "Snowboarding", score: 55 },
          { name: "Ice Hockey", score: 50 },
          { name: "Figure Skating", score: 45 },
          { name: "Curling", score: 25 },
        ],
      },
      {
        name: "Rugby",
        score: 60,
        items: [
          { name: "Rugby Union", score: 55 },
          { name: "Rugby League", score: 45 },
          { name: "Six Nations", score: 60 },
          { name: "Rugby World Cup", score: 70 },
          { name: "Super Rugby", score: 40 },
          { name: "Club Rugby", score: 30 },
        ],
      },
      {
        name: "Golf",
        score: 65,
        items: [
          { name: "PGA Tour", score: 65 },
          { name: "European Tour", score: 55 },
          { name: "The Masters", score: 70 },
          { name: "The Open", score: 65 },
          { name: "Amateur Golf", score: 35 },
          { name: "Mini Golf", score: 40 },
        ],
      },
      {
        name: "Swimming",
        score: 70,
        items: [
          { name: "Freestyle", score: 60 },
          { name: "Butterfly", score: 45 },
          { name: "Backstroke", score: 50 },
          { name: "Breaststroke", score: 55 },
          { name: "Open Water", score: 30 },
          { name: "Competitive Swimming", score: 40 },
        ],
      },
      {
        name: "Athletics",
        score: 60,
        items: [
          { name: "High Jump", score: 45 },
          { name: "Long Jump", score: 50 },
          { name: "Shot Put", score: 35 },
          { name: "Javelin", score: 30 },
          { name: "Pole Vault", score: 25 },
          { name: "Discus", score: 30 },
        ],
      },
      {
        name: "Volleyball",
        score: 55,
        items: [
          { name: "Indoor Volleyball", score: 55 },
          { name: "Beach Volleyball", score: 60 },
          { name: "Professional Leagues", score: 40 },
          { name: "Amateur Leagues", score: 35 },
          { name: "School Volleyball", score: 45 },
        ],
      },
      {
        name: "Baseball",
        score: 70,
        items: [
          { name: "MLB", score: 75 },
          { name: "Minor League", score: 45 },
          { name: "College Baseball", score: 55 },
          { name: "Japanese Baseball", score: 40 },
          { name: "Amateur Baseball", score: 30 },
        ],
      },
      {
        name: "Rowing",
        score: 40,
        items: [
          { name: "Olympic Rowing", score: 40 },
          { name: "University Rowing", score: 35 },
          { name: "Coastal Rowing", score: 20 },
          { name: "Indoor Rowing", score: 25 },
          { name: "Club Rowing", score: 20 },
        ],
      },
      {
        name: "Climbing",
        score: 45,
        items: [
          { name: "Sport Climbing", score: 40 },
          { name: "Bouldering", score: 35 },
          { name: "Traditional Climbing", score: 30 },
          { name: "Ice Climbing", score: 20 },
          { name: "Indoor Climbing", score: 45 },
        ],
      },
    ],
  },
  {
    name: "Music",
    score: 95,
    items: [
      {
        name: "Pop",
        score: 90,
        items: [
          { name: "Contemporary Pop", score: 85 },
          { name: "K-Pop", score: 70 },
          { name: "Indie Pop", score: 60 },
          { name: "Synth Pop", score: 45 },
          { name: "Art Pop", score: 35 },
          { name: "Euro Pop", score: 50 },
          { name: "J-Pop", score: 40 },
          { name: "Teen Pop", score: 65 },
          { name: "Dance Pop", score: 75 },
        ],
      },
      {
        name: "Rock",
        score: 85,
        items: [
          { name: "Classic Rock", score: 75 },
          { name: "Alternative Rock", score: 65 },
          { name: "Metal", score: 55 },
          { name: "Progressive Rock", score: 45 },
          { name: "Punk Rock", score: 50 },
          { name: "Indie Rock", score: 60 },
          { name: "Grunge", score: 45 },
          { name: "Hard Rock", score: 60 },
          { name: "Folk Rock", score: 40 },
          { name: "Psychedelic Rock", score: 35 },
          { name: "Blues Rock", score: 45 },
        ],
      },
      {
        name: "Hip Hop",
        score: 85,
        items: [
          { name: "Old School", score: 60 },
          { name: "Trap", score: 75 },
          { name: "Gangsta Rap", score: 65 },
          { name: "Underground", score: 40 },
          { name: "Alternative Hip Hop", score: 50 },
          { name: "UK Drill", score: 45 },
          { name: "Grime", score: 40 },
        ],
      },
      {
        name: "Electronic",
        score: 75,
        items: [
          { name: "House", score: 70 },
          { name: "Techno", score: 65 },
          { name: "Drum & Bass", score: 55 },
          { name: "Ambient", score: 40 },
          { name: "Trance", score: 45 },
          { name: "Dubstep", score: 50 },
          { name: "EDM", score: 75 },
          { name: "IDM", score: 35 },
          { name: "Garage", score: 40 },
        ],
      },
      {
        name: "Classical",
        score: 60,
        items: [
          { name: "Symphony", score: 55 },
          { name: "Opera", score: 45 },
          { name: "Chamber Music", score: 35 },
          { name: "Baroque", score: 30 },
          { name: "Contemporary Classical", score: 35 },
          { name: "Film Scores", score: 65 },
        ],
      },
      {
        name: "Music Production",
        score: 50,
        items: [
          { name: "Beat Making", score: 45 },
          { name: "Sound Design", score: 35 },
          { name: "Mixing", score: 40 },
          { name: "Mastering", score: 30 },
          { name: "Studio Recording", score: 35 },
        ],
      },
    ],
  },
  {
    name: "Arts & Crafts",
    score: 75,
    items: [
      {
        name: "Painting",
        score: 70,
        items: [
          { name: "Oil Painting", score: 50 },
          { name: "Watercolor", score: 55 },
          { name: "Acrylic", score: 60 },
          { name: "Digital Painting", score: 45 },
          { name: "Gouache", score: 25 },
          { name: "Encaustic", score: 15 },
          { name: "Spray Painting", score: 35 },
          { name: "Chinese Painting", score: 25 },
        ],
      },
      {
        name: "Drawing",
        score: 75,
        items: [
          { name: "Sketching", score: 65 },
          { name: "Illustration", score: 55 },
          { name: "Comic Art", score: 45 },
          { name: "Manga", score: 40 },
          { name: "Character Design", score: 35 },
          { name: "Urban Sketching", score: 30 },
        ],
      },
      {
        name: "Crafts",
        score: 65,
        items: [
          { name: "Knitting", score: 55 },
          { name: "Crochet", score: 50 },
          { name: "Embroidery", score: 45 },
          { name: "Quilting", score: 40 },
          { name: "Pottery", score: 45 },
          { name: "Jewelry Making", score: 40 },
          { name: "Candle Making", score: 35 },
          { name: "Soap Making", score: 30 },
        ],
      },
      {
        name: "Digital Art",
        score: 60,
        items: [
          { name: "3D Modeling", score: 45 },
          { name: "Vector Art", score: 40 },
          { name: "Pixel Art", score: 35 },
          { name: "NFT Art", score: 30 },
          { name: "Motion Graphics", score: 40 },
          { name: "VFX", score: 45 },
          { name: "Digital Sculpting", score: 30 },
        ],
      },
    ],
  },
  {
    name: "Technology",
    score: 85,
    items: [
      {
        name: "Programming",
        score: 75,
        items: [
          { name: "Web Development", score: 70 },
          { name: "Mobile Development", score: 65 },
          { name: "Game Development", score: 55 },
          { name: "AI/ML", score: 50 },
          { name: "DevOps", score: 45 },
          { name: "Blockchain", score: 40 },
          { name: "Cloud Computing", score: 55 },
          { name: "Cybersecurity", score: 50 },
          { name: "Data Science", score: 55 },
        ],
      },
      {
        name: "Gaming",
        score: 85,
        items: [
          { name: "PC Gaming", score: 75 },
          { name: "Console Gaming", score: 80 },
          { name: "Mobile Gaming", score: 85 },
          { name: "VR Gaming", score: 45 },
          { name: "Esports", score: 60 },
          { name: "Retro Gaming", score: 50 },
          { name: "Game Streaming", score: 55 },
          { name: "Speedrunning", score: 30 },
        ],
      },
      {
        name: "Hardware",
        score: 60,
        items: [
          { name: "PC Building", score: 45 },
          { name: "Arduino", score: 30 },
          { name: "Raspberry Pi", score: 35 },
          { name: "3D Printing", score: 40 },
          { name: "Robotics", score: 35 },
          { name: "Drones", score: 45 },
          { name: "Home Automation", score: 50 },
        ],
      },
    ],
  },
  {
    name: "Food & Drink",
    score: 90,
    items: [
      {
        name: "Cooking",
        score: 85,
        items: [
          { name: "Asian Cuisine", score: 75 },
          { name: "European Cuisine", score: 70 },
          { name: "Mediterranean", score: 65 },
          { name: "Baking", score: 70 },
          { name: "BBQ & Grilling", score: 75 },
          { name: "Vegan Cooking", score: 45 },
          { name: "Meal Prep", score: 55 },
          { name: "Sous Vide", score: 30 },
          { name: "Fermentation", score: 25 },
          { name: "Food Photography", score: 40 },
        ],
      },
      {
        name: "Beverages",
        score: 80,
        items: [
          { name: "Coffee", score: 85 },
          { name: "Tea", score: 80 },
          { name: "Wine", score: 70 },
          { name: "Craft Beer", score: 60 },
          { name: "Cocktails", score: 65 },
          { name: "Home Brewing", score: 30 },
          { name: "Whiskey", score: 55 },
          { name: "Kombucha", score: 35 },
        ],
      },
      {
        name: "Baking",
        score: 75,
        items: [
          { name: "Bread Making", score: 60 },
          { name: "Pastry", score: 65 },
          { name: "Cake Decorating", score: 55 },
          { name: "Cookies", score: 70 },
          { name: "Sourdough", score: 45 },
          { name: "Gluten-free", score: 40 },
        ],
      },
    ],
  },
  {
    name: "Outdoors",
    score: 75,
    items: [
      {
        name: "Hiking",
        score: 70,
        items: [
          { name: "Trail Hiking", score: 65 },
          { name: "Mountain Climbing", score: 45 },
          { name: "Backpacking", score: 50 },
          { name: "Urban Hiking", score: 40 },
          { name: "Nature Walking", score: 70 },
        ],
      },
      {
        name: "Gardening",
        score: 65,
        items: [
          { name: "Vegetable Growing", score: 60 },
          { name: "Flower Gardens", score: 65 },
          { name: "Hydroponics", score: 30 },
          { name: "Bonsai", score: 35 },
          { name: "Indoor Plants", score: 70 },
          { name: "Permaculture", score: 25 },
        ],
      },
      {
        name: "Water Sports",
        score: 60,
        items: [
          { name: "Surfing", score: 50 },
          { name: "Swimming", score: 75 },
          { name: "Kayaking", score: 45 },
          { name: "Sailing", score: 35 },
          { name: "Paddleboarding", score: 40 },
          { name: "Scuba Diving", score: 35 },
        ],
      },
      {
        name: "Camping",
        score: 55,
        items: [
          { name: "Traditional Camping", score: 60 },
          { name: "Glamping", score: 45 },
          { name: "Bushcraft", score: 25 },
          { name: "RV Camping", score: 40 },
          { name: "Wild Camping", score: 30 },
        ],
      },
    ],
  },
  {
    name: "Reading & Writing",
    score: 75,
    items: [
      {
        name: "Fiction",
        score: 80,
        items: [
          { name: "Fantasy", score: 65 },
          { name: "Science Fiction", score: 60 },
          { name: "Mystery", score: 70 },
          { name: "Romance", score: 75 },
          { name: "Horror", score: 55 },
          { name: "Historical Fiction", score: 50 },
        ],
      },
      {
        name: "Non-Fiction",
        score: 70,
        items: [
          { name: "Self-Help", score: 65 },
          { name: "Biography", score: 60 },
          { name: "History", score: 55 },
          { name: "Science", score: 50 },
          { name: "Philosophy", score: 45 },
          { name: "Business", score: 60 },
        ],
      },
      {
        name: "Creative Writing",
        score: 50,
        items: [
          { name: "Novel Writing", score: 40 },
          { name: "Poetry", score: 45 },
          { name: "Screenwriting", score: 35 },
          { name: "Blogging", score: 50 },
          { name: "Journalism", score: 45 },
        ],
      },
    ],
  },
  {
    name: "Collecting",
    score: 45,
    items: [
      {
        name: "Stamps",
        score: 30,
        items: [
          { name: "Vintage Stamps", score: 25 },
          { name: "International Stamps", score: 20 },
          { name: "First Day Covers", score: 15 },
        ],
      },
      {
        name: "Coins",
        score: 35,
        items: [
          { name: "Ancient Coins", score: 25 },
          { name: "World Coins", score: 30 },
          { name: "Commemorative Coins", score: 25 },
        ],
      },
      {
        name: "Trading Cards",
        score: 55,
        items: [
          { name: "Pokemon Cards", score: 60 },
          { name: "Magic: The Gathering", score: 45 },
          { name: "Sports Cards", score: 50 },
          { name: "Yu-Gi-Oh!", score: 40 },
        ],
      },
    ],
  },
  {
    name: "Photography",
    score: 70,
    items: [
      {
        name: "Digital Photography",
        score: 75,
        items: [
          { name: "Portrait", score: 65 },
          { name: "Landscape", score: 60 },
          { name: "Street", score: 50 },
          { name: "Wildlife", score: 45 },
          { name: "Macro", score: 35 },
        ],
      },
      {
        name: "Film Photography",
        score: 35,
        items: [
          { name: "35mm", score: 35 },
          { name: "Medium Format", score: 25 },
          { name: "Large Format", score: 20 },
          { name: "Darkroom", score: 15 },
        ],
      },
      {
        name: "Post-Processing",
        score: 50,
        items: [
          { name: "Lightroom", score: 45 },
          { name: "Photoshop", score: 55 },
          { name: "Color Grading", score: 35 },
          { name: "Black & White", score: 40 },
        ],
      },
    ],
  },
];
